# Generated by Django 4.2.8 on 2024-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_category_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('A', 'General'), ('B', 'Technical'), ('C', 'Personal')], default='A', max_length=20),
        ),
    ]
